f = open("D:\python\lecture_7\demo.txt","r")
# f = open("D:/python/lecture_7/demo.txt","r")
# data = f.read()
data = f.read(5)
print(data)
print(type(data))
f.close()


f = open("D:\python\lecture_7\demo.txt","r")
line1 = f.readline()
print(line1)
line2 = f.readline()
print(line2)
line3 = f.readline()
print(line3)
print(type(line1))
f.close()